#if 0
#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
#ifndef MEETINGDOCTORSSDK_SWIFT_H
#define MEETINGDOCTORSSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wduplicate-method-match"
#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if defined(__cplusplus)
#if !defined(SWIFT_NOEXCEPT)
# define SWIFT_NOEXCEPT noexcept
#endif
#else
#if !defined(SWIFT_NOEXCEPT)
# define SWIFT_NOEXCEPT 
#endif
#endif
#if defined(__cplusplus)
#if !defined(SWIFT_CXX_INT_DEFINED)
#define SWIFT_CXX_INT_DEFINED
namespace swift {
using Int = ptrdiff_t;
using UInt = size_t;
}
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="MeetingDoctorsSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class AvatarView;
@class NSCoder;

SWIFT_CLASS("_TtC17MeetingDoctorsSDK16AvatarStatusView")
@interface AvatarStatusView : UIView
@property (nonatomic, weak) IBOutlet AvatarView * _Null_unspecified avatarView;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)unarchiver OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImage;

SWIFT_CLASS("_TtC17MeetingDoctorsSDK10AvatarView")
@interface AvatarView : UIImageView
- (void)awakeFromNib;
- (void)layoutSubviews;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image highlightedImage:(UIImage * _Nullable)highlightedImage OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIColor;

IB_DESIGNABLE
SWIFT_CLASS("_TtC17MeetingDoctorsSDK9BadgeView")
@interface BadgeView : UILabel
/// Background color of the badge
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull badgeColor;
/// Width of the badge border
@property (nonatomic) IBInspectable CGFloat borderWidth;
/// Color of the badge border
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull borderColor;
/// Badge insets that describe the margin between text and the edge of the badge.
@property (nonatomic) IBInspectable CGSize insets;
/// Opacity of the badge shadow
@property (nonatomic) IBInspectable CGFloat shadowOpacityBadge;
/// Size of the badge shadow
@property (nonatomic) IBInspectable CGFloat shadowRadiusBadge;
/// Color of the badge shadow
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull shadowColorBadge;
/// Offset of the badge shadow
@property (nonatomic) IBInspectable CGSize shadowOffsetBadge;
/// Corner radius of the badge. -1 if unspecified. When unspecified, the corner is fully rounded. Default: -1.
@property (nonatomic) IBInspectable CGFloat cornerRadius;
/// Initialize the badge view
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Initialize the badge view
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
/// Initialize the badge view
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
/// Add custom insets around the text
- (CGRect)textRectForBounds:(CGRect)bounds limitedToNumberOfLines:(NSInteger)numberOfLines SWIFT_WARN_UNUSED_RESULT;
/// Draws the label with insets
- (void)drawTextInRect:(CGRect)rect;
/// Draw the background of the badge
- (void)drawRect:(CGRect)rect;
/// Draw the stars in interface builder
- (void)prepareForInterfaceBuilder SWIFT_AVAILABILITY(ios,introduced=8.0);
@end

@class NSString;
@class NSBundle;

SWIFT_CLASS("_TtC17MeetingDoctorsSDK18BaseViewController")
@interface BaseViewController : UIViewController
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end





@class UITextView;

SWIFT_CLASS("_TtC17MeetingDoctorsSDK33ConstrainedHeightTextViewDelegate")
@interface ConstrainedHeightTextViewDelegate : NSObject <UITextViewDelegate>
- (BOOL)textView:(UITextView * _Nonnull)textView shouldChangeTextInRange:(NSRange)range replacementText:(NSString * _Nonnull)text SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class FloatyItem;
enum FloatyOpenAnimationType : NSInteger;
enum FloatyVerticalDirection : NSInteger;
enum FloatyHorizontalDirection : NSInteger;
enum FloatyItemLabelPositionType : NSInteger;
@class UIEvent;

IB_DESIGNABLE
SWIFT_CLASS("_TtC17MeetingDoctorsSDK6Floaty")
@interface Floaty : UIView
/// <code>FloatyItem</code> objects.
@property (nonatomic, copy) NSArray<FloatyItem *> * _Nonnull items;
/// This object’s button size.
@property (nonatomic) CGFloat size;
/// This circleAnimationRadius.
@property (nonatomic) double circleAnimationRadius;
/// This circleAnimationDegreeOffset.
@property (nonatomic) double circleAnimationDegreeOffset;
/// Padding from bottom right of UIScreen or superview.
@property (nonatomic) CGFloat paddingX;
@property (nonatomic) CGFloat paddingY;
/// Automatically closes child items when tapped
@property (nonatomic) IBInspectable BOOL autoCloseOnTap;
/// Automatically closes when tappen on overlay
@property (nonatomic) IBInspectable BOOL autoCloseOnOverlayTap;
/// Runs first item handler directly on tap (without opening menu)
@property (nonatomic) IBInspectable BOOL handleFirstItemDirectly;
/// Places button relative to the Safe Area
@property (nonatomic) IBInspectable BOOL relativeToSafeArea;
/// Degrees to rotate image
@property (nonatomic) IBInspectable CGFloat rotationDegrees;
/// Animation speed of buttons
@property (nonatomic) IBInspectable double animationSpeed;
/// Button color.
@property (nonatomic, strong) IBInspectable UIColor * _Nullable buttonColor;
/// Button highlighted color.
@property (nonatomic, strong) IBInspectable UIColor * _Nullable buttonHighlightedColor;
/// Button shadow color.
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull buttonShadowColor;
/// Button image.
@property (nonatomic, strong) IBInspectable UIImage * _Nullable buttonImage;
/// Plus icon color inside button.
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull plusColor;
/// Background overlaying color.
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull overlayColor;
/// The space between the item and item.
@property (nonatomic) IBInspectable CGFloat itemSpace;
/// Child item’s default size.
@property (nonatomic) IBInspectable CGFloat itemSize;
/// Child item’s default button color.
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull itemButtonColor;
/// Child item’s default title label color.
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull itemTitleColor;
/// Child item’s image color
@property (nonatomic, strong) IBInspectable UIColor * _Nullable itemImageColor;
/// Enable/disable shadow.
@property (nonatomic) IBInspectable BOOL hasShadow;
/// Child item’s default shadow color.
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull itemShadowColor;
///
@property (nonatomic) BOOL closed;
/// Make the menu button draggable
@property (nonatomic) BOOL isDraggable;
/// Whether or not floaty responds to keyboard notifications and adjusts its position accordingly
@property (nonatomic) IBInspectable BOOL respondsToKeyboard;
@property (nonatomic) enum FloatyOpenAnimationType openAnimationType;
@property (nonatomic) enum FloatyVerticalDirection verticalDirection;
@property (nonatomic) enum FloatyHorizontalDirection horizontalDirection;
@property (nonatomic) BOOL friendlyTap;
@property (nonatomic) BOOL sticky;
/// Animations and spacing wll be horizontal not vertical
@property (nonatomic) IBInspectable BOOL supportLanscape;
/// Button selected color.
@property (nonatomic, strong) IBInspectable UIColor * _Nullable selectedColor;
/// Initialize with default property.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// Initialize with custom frame.
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
/// Initialize from storyboard.
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
/// Set size and frame.
- (void)drawRect:(CGRect)rect;
- (void)open;
/// Items close.
- (void)close;
/// Items open or close.
- (void)toggle;
/// Add custom item
- (void)addItemWithItem:(FloatyItem * _Nonnull)item;
/// Add item with title, titlePositon.
/// titlePosition’s default value is left.
- (FloatyItem * _Nonnull)addItemWithTitle:(NSString * _Nonnull)title titlePosition:(enum FloatyItemLabelPositionType)titlePosition;
/// Add item with title.
- (FloatyItem * _Nonnull)addItemWithTitle:(NSString * _Nonnull)title;
/// Add item with title, titlePosition and icon.
/// titlePosition’s default value is left.
- (FloatyItem * _Nonnull)addItem:(NSString * _Nonnull)title icon:(UIImage * _Nullable)icon titlePosition:(enum FloatyItemLabelPositionType)titlePosition;
/// Add item with title and icon.
- (FloatyItem * _Nonnull)addItem:(NSString * _Nonnull)title icon:(UIImage * _Nullable)icon;
/// Add item with title and handler.
- (FloatyItem * _Nonnull)addItemWithTitle:(NSString * _Nonnull)title handler:(void (^ _Nonnull)(FloatyItem * _Nonnull))handler;
/// Add item with titlePosition and handler.
/// titlePosition’s default value is left.
- (FloatyItem * _Nonnull)addItemWithTitle:(NSString * _Nonnull)title titlePosition:(enum FloatyItemLabelPositionType)titlePosition handler:(void (^ _Nonnull)(FloatyItem * _Nonnull))handler;
/// Add item with title, icon or handler.
- (FloatyItem * _Nonnull)addItem:(NSString * _Nonnull)title icon:(UIImage * _Nullable)icon handler:(void (^ _Nonnull)(FloatyItem * _Nonnull))handler;
/// Add item with title, icon, titlePosition or handler.
/// titlePosition’s default value is left
- (FloatyItem * _Nonnull)addItem:(NSString * _Nonnull)title icon:(UIImage * _Nullable)icon titlePosition:(enum FloatyItemLabelPositionType)titlePosition handler:(void (^ _Nonnull)(FloatyItem * _Nonnull))handler;
/// Add item with icon.
- (FloatyItem * _Nonnull)addItemWithIcon:(UIImage * _Nullable)icon;
/// Add item with icon and handler.
- (FloatyItem * _Nonnull)addItemWithIcon:(UIImage * _Nullable)icon handler:(void (^ _Nonnull)(FloatyItem * _Nonnull))handler;
/// Remove item.
- (void)removeItemWithItem:(FloatyItem * _Nonnull)item;
/// Remove item with index.
- (void)removeItemWithIndex:(NSInteger)index;
- (UIView * _Nullable)hitTest:(CGPoint)point withEvent:(UIEvent * _Nullable)event SWIFT_WARN_UNUSED_RESULT;
- (void)observeValueForKeyPath:(NSString * _Nullable)keyPath ofObject:(id _Nullable)object change:(NSDictionary<NSKeyValueChangeKey, id> * _Nullable)_ context:(void * _Nullable)_;
- (void)willMoveToSuperview:(UIView * _Nullable)newSuperview;
- (void)didMoveToSuperview;
@end



@interface Floaty (SWIFT_EXTENSION(MeetingDoctorsSDK))
- (void)layoutSubviews;
@property (nonatomic, copy) NSString * _Nullable accessibilityLabel;
@property (nonatomic, copy) NSString * _Nullable accessibilityHint;
@property (nonatomic, copy) NSString * _Nullable accessibilityValue;
@property (nonatomic, copy) NSArray * _Nullable accessibilityElements;
@end



/// Optional delegate that can be used to be notified whenever the user
/// taps on a FAB that does not contain any sub items.
SWIFT_PROTOCOL("_TtP17MeetingDoctorsSDK14FloatyDelegate_")
@protocol FloatyDelegate
@optional
/// Indicates that the user has tapped on a FAB widget that does not
/// contain any defined sub items.
/// \param floaty The FAB widget that was selected by the user.
///
- (void)emptyFloatySelected:(Floaty * _Nonnull)floaty;
- (BOOL)floatyShouldOpen:(Floaty * _Nonnull)floaty SWIFT_WARN_UNUSED_RESULT;
- (void)floatyWillOpen:(Floaty * _Nonnull)floaty;
- (void)floatyDidOpen:(Floaty * _Nonnull)floaty;
- (BOOL)floatyShouldClose:(Floaty * _Nonnull)floaty SWIFT_WARN_UNUSED_RESULT;
- (void)floatyWillClose:(Floaty * _Nonnull)floaty;
- (void)floatyDidClose:(Floaty * _Nonnull)floaty;
- (BOOL)shallWorkHorizontal SWIFT_WARN_UNUSED_RESULT;
- (void)floatyWillToggled:(Floaty * _Nonnull)floaty;
/// This method has been deprecated. Use floatyWillOpen and floatyDidOpen instead.
- (void)floatyOpened:(Floaty * _Nonnull)floaty;
/// This method has been deprecated. Use floatyWillClose and floatyDidClose instead.
- (void)floatyClosed:(Floaty * _Nonnull)floaty;
@end

typedef SWIFT_ENUM(NSInteger, FloatyHorizontalDirection, open) {
  FloatyHorizontalDirectionLeft = 0,
  FloatyHorizontalDirectionRight = 1,
};


/// Floating Action Button Object’s item.
SWIFT_CLASS("_TtC17MeetingDoctorsSDK10FloatyItem")
@interface FloatyItem : UIView
/// This object’s button size.
@property (nonatomic) CGFloat size;
/// Button color.
@property (nonatomic, strong) UIColor * _Nonnull buttonColor;
/// Title label color.
@property (nonatomic, strong) UIColor * _Nonnull titleColor;
/// Enable/disable shadow.
@property (nonatomic) BOOL hasShadow;
/// Circle Shadow color.
@property (nonatomic, strong) UIColor * _Nonnull circleShadowColor;
/// Title Shadow color.
@property (nonatomic, strong) UIColor * _Nonnull titleShadowColor;
/// If you touch up inside button, it execute handler.
@property (nonatomic, copy) void (^ _Nullable handler)(FloatyItem * _Nonnull);
@property (nonatomic) CGPoint imageOffset;
@property (nonatomic) CGSize imageSize;
/// Item’s title label position.
/// deafult is left
@property (nonatomic) enum FloatyItemLabelPositionType titleLabelPosition;
@property (nonatomic, readonly, strong) UILabel * _Nonnull titleLabel;
/// Item’s title.
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, readonly, strong) UIImageView * _Nonnull iconImageView;
/// Item’s icon.
@property (nonatomic, strong) UIImage * _Nullable icon;
/// Item’s icon tint color change
@property (nonatomic, strong) UIColor * _Null_unspecified iconTintColor;
/// Initialize with default property.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
/// Set size, frame and draw layers.
- (void)drawRect:(CGRect)rect;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

typedef SWIFT_ENUM(NSInteger, FloatyItemLabelPositionType, open) {
  FloatyItemLabelPositionTypeLeft = 0,
  FloatyItemLabelPositionTypeRight = 1,
  FloatyItemLabelPositionTypeTop = 2,
  FloatyItemLabelPositionTypeBottom = 3,
};


/// Floaty dependent on UIWindow.
SWIFT_CLASS("_TtC17MeetingDoctorsSDK13FloatyManager")
@interface FloatyManager : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, FloatyOpenAnimationType, open) {
  FloatyOpenAnimationTypePop = 0,
  FloatyOpenAnimationTypeFade = 1,
  FloatyOpenAnimationTypeSlideLeft = 2,
  FloatyOpenAnimationTypeSlideUp = 3,
  FloatyOpenAnimationTypeSlideDown = 4,
  FloatyOpenAnimationTypeFullCircular = 5,
  FloatyOpenAnimationTypeSemiCircular = 6,
  FloatyOpenAnimationTypeQuadCircular = 7,
  FloatyOpenAnimationTypeNone = 8,
};

typedef SWIFT_ENUM(NSInteger, FloatyVerticalDirection, open) {
  FloatyVerticalDirectionUp = 0,
  FloatyVerticalDirectionDown = 1,
};


/// Floaty dependent on UIWindow.
SWIFT_CLASS("_TtC17MeetingDoctorsSDK20FloatyViewController")
@interface FloatyViewController : UIViewController
- (void)viewDidLoad;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17MeetingDoctorsSDK14MDGradientView")
@interface MDGradientView : UIView
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) Class _Nonnull layerClass;)
+ (Class _Nonnull)layerClass SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC17MeetingDoctorsSDK29MDVideocallBaseViewController")
@interface MDVideocallBaseViewController : BaseViewController
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17MeetingDoctorsSDK36MDVideocallProcessBaseViewController")
@interface MDVideocallProcessBaseViewController : MDVideocallBaseViewController
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (void)viewDidLoad;
/// Close Process
- (void)closeProcess;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17MeetingDoctorsSDK36MDVideocallInformationViewController")
@interface MDVideocallInformationViewController : MDVideocallProcessBaseViewController
- (void)viewDidLoad;
- (void)closeProcess;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end






@class UITableView;
@class NSIndexPath;

@interface MDVideocallProcessBaseViewController (SWIFT_EXTENSION(MeetingDoctorsSDK)) <UITableViewDelegate>
- (void)tableView:(UITableView * _Nonnull)_ didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end

@class UITableViewCell;

@interface MDVideocallProcessBaseViewController (SWIFT_EXTENSION(MeetingDoctorsSDK)) <UITableViewDataSource>
- (NSInteger)tableView:(UITableView * _Nonnull)_ numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)_ cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC17MeetingDoctorsSDK29MedicalHistoryAllergyViewCell")
@interface MedicalHistoryAllergyViewCell : UITableViewCell
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified allergyNameLabel;
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified severityLabel;
@property (nonatomic, strong) IBOutlet UIImageView * _Null_unspecified allergyRate1Image;
@property (nonatomic, strong) IBOutlet UIImageView * _Null_unspecified allergyRate2Image;
@property (nonatomic, strong) IBOutlet UIImageView * _Null_unspecified allergyRate3Image;
@property (nonatomic, strong) IBOutlet UIImageView * _Null_unspecified allergyRate4Image;
@property (nonatomic, strong) IBOutlet UIImageView * _Null_unspecified allergyRate5Image;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@class NSLayoutConstraint;

SWIFT_CLASS("_TtC17MeetingDoctorsSDK29MedicalHistoryGenericViewCell")
@interface MedicalHistoryGenericViewCell : UITableViewCell
@property (nonatomic, strong) IBOutlet NSLayoutConstraint * _Null_unspecified iconImageWidthConstraint;
@property (nonatomic, strong) IBOutlet UIImageView * _Null_unspecified iconImage;
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified optionLabel;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC17MeetingDoctorsSDK25MedicalHistoryIMCViewCell")
@interface MedicalHistoryIMCViewCell : UITableViewCell
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified titleLabel;
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified subtitleLabel;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC17MeetingDoctorsSDK32MedicalHistoryMedicationViewCell")
@interface MedicalHistoryMedicationViewCell : UITableViewCell
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified nameLabel;
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified posologyLabel;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC17MeetingDoctorsSDK37MedicalHistoryVideoCallReportViewCell")
@interface MedicalHistoryVideoCallReportViewCell : UITableViewCell
@property (nonatomic, strong) IBOutlet UIImageView * _Null_unspecified doctorImage;
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified reportDescription;
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified doctorName;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC17MeetingDoctorsSDK11MessageView")
@interface MessageView : UICollectionReusableView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)_ OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17MeetingDoctorsSDK21MessageDateFooterView")
@interface MessageDateFooterView : MessageView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)_ OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17MeetingDoctorsSDK21MessageDateHeaderView")
@interface MessageDateHeaderView : MessageView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)_ OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC17MeetingDoctorsSDK13NPSBannerView")
@interface NPSBannerView : UIView
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)unarchiver SWIFT_UNAVAILABLE;
@end





SWIFT_CLASS("_TtC17MeetingDoctorsSDK19PhotoViewController")
@interface PhotoViewController : BaseViewController
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@class UIScrollView;

@interface PhotoViewController (SWIFT_EXTENSION(MeetingDoctorsSDK)) <UIScrollViewDelegate>
- (UIView * _Nullable)viewForZoomingInScrollView:(UIScrollView * _Nonnull)_ SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC17MeetingDoctorsSDK10StatusView")
@interface StatusView : UIView
- (void)awakeFromNib;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17MeetingDoctorsSDK32TermsAndConditionsViewController")
@interface TermsAndConditionsViewController : UIViewController
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


/// A <code>TitledSupplementaryView</code> is a <code>UICollectionReusableView</code> subclass with a single <code>UILabel</code>.
/// It is intended for use as an analog to a <code>UITableView</code> header title.
/// These views can be used with <code>TitledSupplementaryViewConfig</code>.
SWIFT_CLASS("_TtC17MeetingDoctorsSDK23TitledSupplementaryView")
@interface TitledSupplementaryView : UICollectionReusableView
/// :nodoc:
@property (nonatomic, strong) UIColor * _Nullable backgroundColor;
/// :nodoc:
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
/// :nodoc:
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
/// :nodoc:
- (void)prepareForReuse;
/// :nodoc:
- (void)layoutSubviews;
@end
























IB_DESIGNABLE
SWIFT_CLASS("_TtC17MeetingDoctorsSDK18UIImageViewAligned")
@interface UIImageViewAligned : UIImageView
@property (nonatomic, strong) UIImage * _Nullable image;
@property (nonatomic, strong) UIImage * _Nullable highlightedImage;
/// The option to align the content to the top.
/// It is available in Interface Builder and should not be set programmatically. Use <code>alignment</code> property if you want to set alignment outside Interface Builder.
@property (nonatomic) IBInspectable BOOL alignTop;
/// The option to align the content to the left.
/// It is available in Interface Builder and should not be set programmatically. Use <code>alignment</code> property if you want to set alignment outside Interface Builder.
@property (nonatomic) IBInspectable BOOL alignLeft;
/// The option to align the content to the right.
/// It is available in Interface Builder and should not be set programmatically. Use <code>alignment</code> property if you want to set alignment outside Interface Builder.
@property (nonatomic) IBInspectable BOOL alignRight;
/// The option to align the content to the bottom.
/// It is available in Interface Builder and should not be set programmatically. Use <code>alignment</code> property if you want to set alignment outside Interface Builder.
@property (nonatomic) IBInspectable BOOL alignBottom;
@property (nonatomic, getter=isHighlighted) BOOL highlighted;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image highlightedImage:(UIImage * _Nullable)highlightedImage OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (void)didMoveToSuperview;
- (void)didMoveToWindow;
@end



@interface UILabel (SWIFT_EXTENSION(MeetingDoctorsSDK))
- (void)awakeFromNib;
@end



@interface UINavigationBar (SWIFT_EXTENSION(MeetingDoctorsSDK))
- (void)awakeFromNib;
@end










@interface UITextField (SWIFT_EXTENSION(MeetingDoctorsSDK))
- (void)awakeFromNib;
@end


@interface UITextView (SWIFT_EXTENSION(MeetingDoctorsSDK))
- (void)awakeFromNib;
@end

@class NSTextStorage;

@interface UITextView (SWIFT_EXTENSION(MeetingDoctorsSDK)) <NSTextStorageDelegate>
- (void)textStorage:(NSTextStorage * _Nonnull)_ didProcessEditing:(NSTextStorageEditActions)editedMask range:(NSRange)_ changeInLength:(NSInteger)_;
@end
















#endif
#if defined(__cplusplus)
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
